$(document).ready(function(){
    $(".header").hover(function(){
        $(".header").slideUp(7000);
        $(".header").slideDown(7000);
    })
});
$(document).ready(function(){
    $(".button").click(function(){
        $(".container-menu").show();
    })
    $(".view-menu").click(function(){
        $(".container-menu").show();
    })
    $(".contact-us").click(function(){
        $(".footer").show();
    })
})